export const ACTION_TYPE = {  
  SET_POSTPONED: "SET_POSTPONED",
  SET_ATWORK: "SET_ATWORK",
  SET_DONE: "SET_DONE",
  SET_SEARCH_PHRASE: "SET_SEARCH_PHRASE",
  UPDATE_SEARCH: 'UPDATE_SEARCH',
  SET_ALL_TODO: 'SET_ALL_TODO',  
  DELETE_SEARCH_PHRASE: "DELETE_SEARCH_PHRASE", 
};
